### PR TITLE
add function to get root level to abstract assignment

### PR DESCRIPTION
**Pull request by rkaminsk**
Hi, is this pull request okay with you? If yes, can you merge or give me the okay to merge? Note that I did not find a nice way to deal with submodules. libpotassco has to be merged first and the url of the submodule updated in this request afterwards.

### CODE REVIEW

**Comment by BenKaufmann** [comment]
I merged the PR in libpotassco and I'm fine with this PR. So feel free to update and merge it.

**Comment by rkaminsk** [comment]
You were commenting on the naming of the function but already merged the request. Are you thinking more about the clingo APIs regarding the naming here?

I went with `rootLevel` because that is what you used in the solver and I heard it numerous times. Using `fixed` alone does not seem nice to me because it is hard to make the association to levels from the function signature. Something like `fixedLevels` might work. Also in the description of `isFixed` you used top level, so `topLevel` might also be a candidate.

**Comment by BenKaufmann** [comment]
> You were commenting on the naming of the function but already merged the request. Are you thinking more about the clingo APIs regarding the naming here?

No. I simply misread the comment and thought the function was supposed to return the size of the top-level, i.e. the number of fixed literals but since that is not the case, I'm fine with the name.

Note that there is a difference between `topLevel` and `rootLevel`. The former always means level 0 and a literal is fixed iff it is implied on the `topLevel`. On the other hand, `rootLevel` is 
the "top level" of the current search and is > 0, whenever the search runs "under some assumptions" (i.e. with a non empty guiding path).

**Comment by rkaminsk** [comment]
I started to think that isFixed also returns true for literals assigned within the root level. I am going to merge this some time later. 

Also, in the future I will simply put a branch in the clasp repository instead of using a fork. This makes it easier to work with submodules. I won't merge anything without your okay, though.

**Pull request merged**
